#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

// Tap Dance declarations
enum {
    TD_COMMA_SEMICOLON,
    TD_PERIOD_COLON,
    TD_QUOT,
};

void period_colon(qk_tap_dance_state_t *state, void *user_data) {
	switch (state->count)
	{
	case 1:
		SEND_STRING(".");
		break;
	case 2:
		SEND_STRING(":");
		break;
	case 3:
		SEND_STRING("...");
		break;
	}
}

void quot_doublequot(qk_tap_dance_state_t *state, void *user_data) {
    switch (state->count)
    {
    case 1:
        SEND_STRING("'");
        break;
    case 2:
        SEND_STRING("\"");
        break;
    }
}

// Tap Dance definitions
qk_tap_dance_action_t tap_dance_actions[] = {
    // Tap once for Escape, twice for Caps Lock
    [TD_COMMA_SEMICOLON] = ACTION_TAP_DANCE_DOUBLE(KC_COMMA, KC_SEMICOLON),
	[TD_PERIOD_COLON] = ACTION_TAP_DANCE_FN(period_colon),
    [TD_QUOT] = ACTION_TAP_DANCE_FN(quot_doublequot)

};

LEADER_EXTERNS();

void matrix_scan_user(void) {
  LEADER_DICTIONARY() {
    leading = false;
    leader_end();

    SEQ_ONE_KEY(KC_F) {
      // Anything you can do in a macro.
      SEND_STRING("QMK is awesome.");
    }
    SEQ_TWO_KEYS(KC_D, KC_D) {
      SEND_STRING(SS_LCTL("a") SS_LCTL("c"));
    }
    SEQ_THREE_KEYS(KC_D, KC_D, KC_S) {
      SEND_STRING("https://start.duckduckgo.com\n");
    }
    SEQ_TWO_KEYS(KC_A, KC_S) {
      register_code(KC_LGUI);
      register_code(KC_S);
      unregister_code(KC_S);
      unregister_code(KC_LGUI);
    }
    SEQ_TWO_KEYS(KC_W, KC_N) {
        register_code(KC_LGUI);
        register_code(KC_LCTL);
        register_code(KC_RIGHT);
        unregister_code(KC_RIGHT);
        unregister_code(KC_LCTL);
        unregister_code(KC_LGUI);
    }
    SEQ_TWO_KEYS(KC_W, KC_P) {
        register_code(KC_LGUI);
        register_code(KC_LCTL);
        register_code(KC_LEFT);
        unregister_code(KC_LEFT);
        unregister_code(KC_LCTL);
        unregister_code(KC_LGUI);
    }
  }
}

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x5_2(
            KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, 
            KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_LEAD, 
            KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, TD(TD_COMMA_SEMICOLON), TD(TD_PERIOD_COLON), KC_SLSH, 
            LT(1,KC_SPC), OSM(MOD_LSFT), KC_BSPC, OSM(MOD_LCTL)),
	[1] = LAYOUT_split_3x5_2(
            KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_MINS, KC_EQL, 
            KC_LCBR, KC_RCBR, KC_COLN, LSFT_T(KC_ESC), KC_TAB, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_ENT, 
            KC_LPRN, KC_RPRN, KC_LBRC, KC_RBRC, KC_BSLS, KC_PIPE, TD(TD_QUOT), KC_GRV, OSM(MOD_LGUI), TO(2), 
            KC_NO, KC_NO, OSM(MOD_RALT), OSM(MOD_LCTL)),
	[2] = LAYOUT_split_3x5_2(KC_ENT, KC_7, KC_8, KC_9, KC_HOME, KC_INS, KC_F7, KC_F8, KC_F9, KC_F10, KC_0, KC_1, KC_2, KC_3, KC_DOT, KC_COMM, KC_F4, KC_F5, KC_F6, KC_F11, KC_SPC, KC_4, KC_5, KC_6, KC_END, KC_DEL, KC_F1, KC_F2, KC_F3, KC_F12, TO(0), OSM(MOD_LSFT), KC_BSPC, OSM(MOD_LCTL)),
	[3] = LAYOUT_split_3x5_2(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_VOLD, KC_VOLU, KC_MUTE, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_BRID, KC_BRIU, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO),
};

