#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum {
    TD_COMMA,
    TD_DOT,
};

tap_dance_action_t tap_dance_actions[] = {
    // Tap once for Escape, twice for Caps Lock
    [TD_COMMA] = ACTION_TAP_DANCE_DOUBLE(KC_COMM, KC_SCLN),
    [TD_DOT] = ACTION_TAP_DANCE_DOUBLE(KC_DOT, KC_COLN),
};

void leader_start_user(void) {
    // Do something when the leader key is pressed
}

void leader_end_user(void) {
    if (leader_sequence_one_key(KC_F)) {
        // Leader, f => Types the below string
        SEND_STRING("QMK is awesome.");
    } else if (leader_sequence_one_key(KC_DOT)) {
        tap_code16(KC_COLN);
    } else if (leader_sequence_one_key(KC_COMM)) {
        tap_code16(KC_SCLN);
    } else if (leader_sequence_two_keys(KC_D, KC_D)) {
        // Leader, d, d => Ctrl+A, Ctrl+C
        SEND_STRING(SS_LCTL("a") SS_LCTL("c"));
    } else if (leader_sequence_three_keys(KC_D, KC_D, KC_S)) {
        // Leader, d, d, s => Types the below string
        SEND_STRING("https://start.duckduckgo.com\n");
    } else if (leader_sequence_two_keys(KC_A, KC_S)) {
        // Leader, a, s => GUI+S
        tap_code16(LGUI(KC_S));
    }
}

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

[0] = LAYOUT_split_3x5_2(
    KC_Q,   KC_W,   KC_F,   KC_P,   KC_B,   KC_J,   KC_L,   KC_U,           KC_Y,       QK_LEAD,
    KC_A,   KC_R,   KC_S,   KC_T,   KC_G,   KC_M,   KC_N,   KC_E,           KC_I,       KC_O,
    KC_Z,   KC_X,   KC_C,   KC_D,   KC_V,   KC_K,   KC_H,   KC_COMM, KC_DOT,   KC_SLSH,
                            LCTL_T(KC_SPC), TL_LOWR, TL_UPPR, OSM(MOD_LSFT)
),

[1] = LAYOUT_split_3x5_2(
    KC_BRIU, KC_7, KC_8, KC_9, KC_TAB, KC_INS, KC_PGDN, KC_PGUP, KC_DEL, KC_BSPC,
    KC_BRID, KC_4, KC_5, KC_6, KC_ESC, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_ENT,
    KC_0, KC_1, KC_2, KC_3, CW_TOGG, KC_HOME, KC_PSCR, LSFT(KC_PSCR), KC_END, LCTL(KC_ENT),
                        KC_NO, KC_TRNS, KC_TRNS, OSM(MOD_LALT)
),

[2] = LAYOUT_split_3x5_2(
    KC_VOLU, KC_AMPR, KC_ASTR, KC_PLUS, KC_LPRN, KC_RPRN, KC_QUOT, KC_DQUO, KC_RALT, LCTL(KC_BSPC),
    KC_MUTE, KC_DLR, KC_PERC, KC_CIRC, KC_LBRC, KC_RBRC, KC_MINS, KC_EQL, KC_GRV, KC_NO,
    KC_VOLD, KC_EXLM, KC_AT, KC_HASH, KC_LCBR, KC_RCBR, KC_UNDS, KC_PIPE, KC_TILD, KC_BSLS,
                        KC_NO, KC_TRNS, KC_TRNS, KC_NO
),

[3] = LAYOUT_split_3x5_2(
    QK_BOOT, LGUI(KC_7), LGUI(KC_8), LGUI(KC_9), KC_NO, KC_NO, LGUI(KC_L), LGUI(KC_ENT), SGUI(KC_Q), QK_BOOT,
    KC_NO, LGUI(KC_4), LGUI(KC_5), LGUI(KC_6), KC_NO, MO(4), KC_LSFT, LGUI(KC_P), SGUI(KC_P), KC_NO,
    KC_NO, LGUI(KC_1), LGUI(KC_2), LGUI(KC_3), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
                        KC_NO, KC_TRNS, KC_TRNS, KC_NO
),

[4] = LAYOUT_split_3x5_2(
    KC_F10, KC_F7, KC_F8, KC_F9, KC_NO, KC_NO, LCA(KC_F7), LCA(KC_F8), LCA(KC_F9), KC_NO,
    KC_F11, KC_F4, KC_F5, KC_F6, OSM(MOD_LCTL|MOD_LALT), KC_TRNS, LCA(KC_F4), LCA(KC_F5), LCA(KC_F6), KC_NO,
    KC_F12, KC_F1, KC_F2, KC_F3, KC_NO, KC_NO, LCA(KC_F1), LCA(KC_F2), LCA(KC_F3), KC_NO,
                        KC_NO, KC_TRNS, KC_TRNS, KC_NO
)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)





